Actionlog
ricochet1k/screeps-client pull request #16
Opened 2017-04-20 14:45 UTC by FlyingPiMonster

Adds most of the actions from #7. I haven't gotten around to testing all of them yet, but I will soon.

2017-05-18 20:28 UTC, ricochet1k requested changes
Looks pretty good, fix a few things and I'll merge this. Sorry it took me so long to review.

2017-05-18 20:28 UTC, ricochet1k commented on src/scripts/skins/original/creep.js
> +			say(this.g, obj.saying.message);
Move this into the `case 'say'` above, and get rid of obj.saying.

2017-05-18 20:28 UTC, ricochet1k commented on src/scripts/actions.js
> +		g.beginFill(color, v);
It's probably much better to set g.alpha instead of redrawing every frame

2017-05-18 20:28 UTC, ricochet1k commented on src/scripts/actions.js
> +	color = color || 0xffff00;
This should be added as a default value to the color parameter above, like this: `, color = 0xffff00) {`

2017-05-18 22:19 UTC, FlyingPiMonster commented
I've made the changes you suggested. (I'm new to PixiJS, thanks for catching my mistakes!)

2017-05-19 14:58 UTC, ricochet1k approved these changes

2017-05-19 14:59 UTC, merged